name: Sonar

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  shared:
    if: github.repository == 'pantos-io/client-cli'
    uses: pantos-io/ci-workflows/.github/workflows/sonar.yml@v1
    secrets: inherit

